### ISSUE TITLE
0.6.0 throws ReflectionTypeLoadException | Could not load file or assembly Microsoft.VisualStudio.Coverage.CoreLib.Net Version=16.9.0.0

### ISSUE THREAD

**Issue by gojanpaolo** [SwissLife-OSS/snapshooter#125]
0.6.0 seems to have introduced an exception when using the latest version of `Microsoft.NET.Test.Sdk` (16.9.1). There is no exception when `Microsoft.NET.Test.Sdk` is downgraded to 16.8.3 or when Snapshooter is downgraded to 0.5.8.

I created a sample repo that reproduces the issue: https://github.com/gojanpaolo/snapshooter-0.6.0-visualstudio-coverage-bug

Below are the results for Snapshooter 0.5.8 and 0.6.0 by running `dotnet test` (issue also happens when tests are ran in Visual Studio)

0.5.8
```
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 20 ms - snapshooter-0.5.8.dll (net5.0)
```

0.6.0
```
  Failed snapshooter_0_6_0.Tests.Test [21 ms]
  Error Message:
   System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.VisualStudio.Coverage.CoreLib.Net, Version=16.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Stack Trace:
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Snapshooter.Core.Serialization.GlobalSnapshotSettingsResolver.<>c.<GetConfiguration>b__0_0(Assembly s)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Snapshooter.Core.Serialization.GlobalSnapshotSettingsResolver.GetConfiguration()
   at Snapshooter.Core.Serialization.SnapshotSerializer.GetSettings(ISnapshotSettingsResolver snapshotSettingsResolver)
   at Snapshooter.Core.Serialization.SnapshotSerializer..ctor(ISnapshotSettingsResolver settingsResolver)
   at Snapshooter.Xunit.Snapshot.get_Snapshooter()
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, Func`2 matchOptions)
   at Snapshooter.Xunit.SnapshotExtension.MatchSnapshot(Object currentResult, Func`2 matchOptions)
   at snapshooter_0_6_0.Tests.Test() in C:\@dev\snapshooter-0.6.0-visualstudio-coverage-bug\snapshooter-0.6.0\Tests.cs:line 8

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 21 ms - snapshooter-0.6.0.dll (net5.0)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1909

**Comment by gojanpaolo** [comment]
This may be an issue on Microsoft.NET.Test.Sdk because running the following code on 16.9.1 will throw the exception:

```
AppDomain.CurrentDomain.GetAssemblies().SelectMany(s => s.GetTypes()).ToList();
```

**Comment by gojanpaolo** [comment]
It looks like this can be fixed in `GlobalSnapshotSettingsResolver` by updating the code like so:

```
var typesExtendingSettings = AppDomain.CurrentDomain.GetAssemblies()
    .SelectMany(s =>
    {
        try
        {
            return s.GetTypes();
        }
        catch (ReflectionTypeLoadException e)
        {
            return e.Types;
        }
    })
    .Where(p =>
        type.IsAssignableFrom(p) &&
        p.IsClass &&
        p.GetConstructor(Type.EmptyTypes) != null)
    .ToList();
```

see also https://stackoverflow.com/a/7889272/5588197
