### ISSUE TITLE
Snapshot Test fails on Azure

### ISSUE THREAD

**Issue by tsinghammer** [SwissLife-OSS/Snapshooter#149]
**Describe the bug**
I have two Snapshooter tests which's output are dictionaries. Locally everything works fine, the snapshot files are being generated the first time and then match from then on.
However the same tests run on Azure fail with the following exception:

**Stack trace**
```
[xUnit.net 00:00:03.95]     Mapping.Tests.Test.MapperTest.Test_Bug_460395_oa136372 [FAIL]
  Failed Mapping.Tests.Test.MapperTest.Test_Bug_460395_oa136372 [989 ms]
  Error Message:
   Snapshooter.Exceptions.SnapshotTestException : The snapshot full name could not be evaluated. This error can occur, if you use the snapshot match within a async test helper child method. To solve this issue, use the Snapshot.FullName directly in the unit test to get the snapshot name, then reach this name to your Snapshot.Match method.
  Stack Trace:
     at Snapshooter.Xunit.XunitSnapshotFullNameReader.ReadSnapshotFullName()
   at Snapshooter.SnapshotFullNameResolver.ResolveSnapshotFullName(String snapshotName, String snapshotNameExtension)
   at Snapshooter.Snapshooter.ResolveSnapshotFullName(String snapshotName, SnapshotNameExtension snapshotNameExtension)
   at Snapshooter.Xunit.Snapshot.FullName()
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, Func`2 matchOptions)
```

The tests are not async.
Do you have any idea what could cause this?
Btw. there are already other Snapshooter tests in this project running successfully both locally and on Azure.

**Comment by tsinghammer** [comment]
It seems that a foreach loop in the test code is causing the issue.
This code succeeds on Azure:
`   [Fact]
    public void Test_Bug_460395_oa136372()
    {
        List<Test> testItems = new();
        // foreach (string item in new string[] { "test1", "test2", "test3" })
        // {
        //     testItems.Add(new Test(item));
        // }
        testItems = new string[] { "test1", "test2", "test3" }.Select(x => new Test(x)).ToList();
        Snapshot.Match(testItems);
    }`
    
    However this one fails:
    `[Fact]
    public void Test_Bug_460395_oa136372()
    {
        List<Test> testItems = new();
        foreach (string item in new string[] { "test1", "test2", "test3" })
        {
            testItems.Add(new Test(item));
        }
        // testItems = new string[] { "test1", "test2", "test3" }.Select(x => new Test(x)).ToList();
        Snapshot.Match(testItems);
    }`

**Comment by tsinghammer** [comment]
Stack trace:
```
 Failed Mapping.Tests.SobradoOfferTest.GeneralPlanMapperTest.Test_Bug_460395_oa136372 [183 ms]
  Error Message:
   Snapshooter.Exceptions.SnapshotTestException : The snapshot full name could not be evaluated. This error can occur, if you use the snapshot match within a async test helper child method. To solve this issue, use the Snapshot.FullName directly in the unit test to get the snapshot name, then reach this name to your Snapshot.Match method.
  Stack Trace:
     at Snapshooter.Xunit.XunitSnapshotFullNameReader.ReadSnapshotFullName()
   at Snapshooter.SnapshotFullNameResolver.ResolveSnapshotFullName(String snapshotName, String snapshotNameExtension)
   at Snapshooter.Snapshooter.ResolveSnapshotFullName(String snapshotName, SnapshotNameExtension snapshotNameExtension)
   at Snapshooter.Xunit.Snapshot.FullName()
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, Func`2 matchOptions)
```

**Comment by tsinghammer** [comment]
I have an additional problem with different behavior local vs Azure:
There is a difference in the decimal places being rendered:

`                                 ↓ (pos 6773)
Expected: ···\"DecRangeMin\": 0.0,\n        \"DecRangeMax\": 99.000000,\n ···
Actual:   ···\"DecRangeMin\": 0.000000,\n        \"DecRangeMax\": 99.00000···
`
