### ISSUE TITLE
Snapshot path problem on Linux build agent

### ISSUE THREAD

**Issue by BalintBanyasz** [SwissLife-OSS/snapshooter#196]
**Describe the bug**
Looks like the snapshot folder isn't resolved properly, so Snapshooter tries to create a directory it doesn't have permissions for.

**To Reproduce**
Using:
 - Snapshooter.Xunit 0.14.1
 - xunit 2.7.0
 - dotnet 8.0
 - Azure ubuntu-latest image

Test passes on development machine (Windows 11, VS2022) but fails on Linux CI run. Snapshot file is checked in to the repository, SNAPSHOOTER_STRICT_MODE is set to true.

**Expected behavior**
The existing snaphot should be resolved correctly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS (ubuntu-22.04 v20240225.1.0 image) Azure hosted agent

**Additional context**
```
  Error Message:
   System.UnauthorizedAccessException : Access to the path '/_' is denied.
---- System.IO.IOException : Permission denied
  Stack Trace:
     at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Snapshooter.Core.SnapshotFileHandler.CreateFolderIfNotExist(String folderPath)
   at Snapshooter.Core.SnapshotFileHandler.EnsureSnapshotFolder(SnapshotFullName snapshotFullName)
   at Snapshooter.Core.SnapshotFileHandler.TryReadSnapshot(SnapshotFullName snapshotFullName, String& snapshotData)
   at Snapshooter.SnapshotAssert.AssertSnapshot(Object currentResult, SnapshotFullName snapshotFullName, MatchOptions matchOptions)
   at Snapshooter.Snapshooter.AssertSnapshot(Object currentResult, SnapshotFullName snapshotFullName, Func`2 matchOptionsSettings)
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, Func`2 matchOptions)
   at Snapshooter.Xunit.Snapshot.Match[T](T currentResult, Func`2 matchOptions)
```

**Comment by Jetski5822** [comment]
Were you able to fix this? I have hit this too

**Comment by tobias-tengler** [comment]
Running into a similar thing. Our paths start with `/_/`, but we don't get any permission exceptions (as far as we can see).

**Comment by mtsfoni** [comment]
I also ran into this problem.

Interestingly, it seemed to work until roughly 5 months ago, the last change to our codebase was 7 months ago. 

So I can only assume that something regarding the OS or GitHub workflows caused the problem.

The `/_/` seems pretty bogus, however. The actual path should rather be: `/Users/runner/work/project-name/project-name/...`. Maybe it has always been `/_/` but it only started being a problem after an OS Update?



```
  Error Message:
   System.UnauthorizedAccessException : Access to the path '/_/tests/CycloneDX.Spdx.Interop.Tests/__snapshots__' is denied.
---- System.IO.IOException : Permission denied
  Stack Trace:
     at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Snapshooter.Core.SnapshotFileHandler.CreateFolderIfNotExist(String folderPath)
   at Snapshooter.Core.SnapshotFileHandler.EnsureSnapshotFolder(SnapshotFullName snapshotFullName)
   at Snapshooter.Core.SnapshotFileHandler.TryReadSnapshot(SnapshotFullName snapshotFullName, String& snapshotData)
   at Snapshooter.SnapshotAssert.AssertSnapshot(Object currentResult, SnapshotFullName snapshotFullName, MatchOptions matchOptions)
   at Snapshooter.Snapshooter.AssertSnapshot(Object currentResult, SnapshotFullName snapshotFullName, Func`2 matchOptionsSettings)
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, SnapshotFullName snapshotFullName, Func`2 matchOptions)
   at Snapshooter.Xunit.Snapshot.Match(Object currentResult, SnapshotNameExtension snapshotNameExtension, Func`2 matchOptions)
   at Snapshooter.Xunit.Snapshot.Match[T](T currentResult, SnapshotNameExtension snapshotNameExtension, Func`2 matchOptions)
...
----- Inner Stack Trace -----
```

**Comment by andreas-hilti** [comment]
@mtsfoni From what I can see the directory is determined here:
https://github.com/SwissLife-OSS/snapshooter/blob/94f9c77703a05e0d03b02aba9adb68d655fab820/src/Snapshooter.Xunit/XunitSnapshotFullNameReader.cs#L24
It fetches the stack frames
`StackFrame[] stackFrames = new StackTrace(true).GetFrames();`
and searches for methods that have the Theory or Fact attribute and gets the corresponding directory.
For me, this is working, and if I execute this manually, it results in something like this:
![grafik](https://github.com/SwissLife-OSS/snapshooter/assets/69210561/842b47a9-a8ef-4c67-bca4-833c34d04c24)
Don't know what goes wrong, but you see further down often the "/_/" start in the directory name.

**Comment by andreas-hilti** [comment]
Note the definition of StackFrame.GetFileName:
> Gets the file name that contains the code that is executing. This information is typically extracted from the debugging symbols for the executable.

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stackframe.getfilename?view=net-6.0

i.e. it has to do with the debug information that is available while running the test.

**Comment by mtsfoni** [comment]
I assume something happens in the GitHub actions environment causing the .pdbs to come out with unexpected paths.

I found this [work around,](https://github.com/CycloneDX/cyclonedx-dotnet-library/commit/a27d9238e253681fcfbcfa2a3585f27974eb44e0) which currently is good enough for me.

**Comment by CedricHg** [comment]
The path is of the form ```/_/src/...``` on a CI because of the deterministic build option that is true by default for CI builds. This path is stored in the PDB, Snapshooter reads it exactly like that, and thus tries to access a "/_" directory which does not exist.

To get around this I wrote a custom Snapshot static class, basically a copy of the Xunit Snapshot class (https://github.com/SwissLife-OSS/snapshooter/blob/master/src/Snapshooter.Xunit/Snapshot.cs). The difference is it accepts a sourceFile parameter with a ```[CallerFilePath] ``` attribute, and the construction of the ```Snapshooter``` class receives an own ```ISnapshotFullnameReader``` implementation.

The path to ```__snapshots__``` is determined like this:

```
        private const string Marker = ".Tests";

        public SnapshotFullName ReadSnapshotFullName()
        {
            SnapshotFullName? snapshotFullName = null;
            StackFrame[] stackFrames = new StackTrace(true).GetFrames();

            foreach (StackFrame stackFrame in stackFrames)
            {
                MethodBase? method = stackFrame.GetMethod();
                if (method != null && IsXunitTestMethod(method))
                {
                    snapshotFullName = new SnapshotFullName(method.ToName(), DetermineDirectory());
                    break;
                }

                MethodBase? asyncMethod = EvaluateAsynchronMethodBase(method);
                if (asyncMethod != null && IsXunitTestMethod(asyncMethod))
                {
                    snapshotFullName = new SnapshotFullName(asyncMethod.ToName(), DetermineDirectory());
                    break;
                }
            }

            if (snapshotFullName == null)
            {
                throw new SnapshotTestException(
                    "The snapshot full name could not be evaluated. " +
                    "This error can occur, if you use the snapshot match " +
                    "within a async test helper child method. To solve this issue, " +
                    "use the Snapshot.FullName directly in the unit test to " +
                    "get the snapshot name, then reach this name to your " +
                    "Snapshot.Match method.");
            }

            snapshotFullName = LiveUnitTestingDirectoryResolver
                .CheckForSession(snapshotFullName);

            return snapshotFullName;
        }

        private string DetermineDirectory()
        {
            var assemblyLocation = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!;
            var testDirectory = Path.GetDirectoryName(sourceFile)!;

            var idx = testDirectory.IndexOf(Marker, StringComparison.OrdinalIgnoreCase);
            if (idx < 0)
                throw new InvalidOperationException($"Could not locate '{Marker}' segment in '{testDirectory}'.");

            var projectDirectory = testDirectory.Substring(0, idx + Marker.Length);
            var testDirectorySuffix = testDirectory.Replace(projectDirectory, string.Empty).Replace("\\", string.Empty);
            var combination = Path.Combine(assemblyLocation, testDirectorySuffix);
            return combination;
        }
```

This is a bit too wonky for general usage probably, we have a convention that all test projects end with ".Tests", which is what that Marker string is. What the code does is combine the assembly location with the source file location to get a correct full path. On our build agent, the assembly location could be eg ```/home/work/somefolder/Tests/bin/Release/net10.0``` and the source file location could be ```/_/src/Tests/SomeSubFolder/AnotherSubFolder```. The combined result becomes ```/home/work/somefolder/Tests/bin/Release/net10.0/SomeSubFolder/AnotherSubFolder``` which is exactly the directory where the ```__snapshots__``` subfolder can be found.

This works ok for us, but would likely need alterations to implement in this library. It would make sense to me that Snapshooter should handle this case correctly out of the box though.
